sources += files(
    'logical_get.cpp',
    'logical_inner_join.cpp',
    'logical_filter.cpp',
    'logical_projection.cpp',
    'logical_limit.cpp',
    'physical_table_scan.cpp',
    'physical_index_scan.cpp',
    'physical_nested_loop_join.cpp',
    'physical_filter.cpp',
    'physical_projection.cpp',
    'physical_sort.cpp',
    'physical_aggregate.cpp',
    'physical_limit.cpp',
    'operators.cpp'
)
